apiVersion: v1
kind: Service
metadata:
  name: waf
spec:
  ports:
    - port: 8080
  selector:
    app: waf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waf
  template:
    metadata:
      labels:
        app: waf
    spec:
      containers:
        - name: waf
          image: custom-waf
          env:
            - name: PROXY_HOST
              value: http://api:5000
